name: Build SiriRevive Windows EXE

on:
  push:
    branches: [ "main" ] # Запускать сборку при каждом обновлении кода
  workflow_dispatch: # Позволяет запускать сборку кнопкой вручную

jobs:
  build:
    runs-on: windows-latest # Просим у GitHub сервер на Windows!

    steps:
    - name: Скачиваем код из репозитория
      uses: actions/checkout@v3

    - name: Устанавливаем Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Устанавливаем библиотеки
      run: |
        python -m pip install --upgrade pip
        pip install dnslib biplist groq pyinstaller

    - name: Собираем EXE файл
      run: |
        pyinstaller --noconsole --onefile --add-data "guzzoni.crt;." --add-data "guzzoni.key;." --add-data "libspeex.dll;." SiriRevive.py

    - name: Сохраняем готовый EXE
      uses: actions/upload-artifact@v3
      with:
        name: SiriRevive_Windows_EXE
        path: dist/SiriRevive.exe
